services:
  redu:
    build:
      context: .  # assumes Dockerfile is in current directory
    container_name: redu
    ports:
      - "3000:3000"  # host:container
    depends_on:
      - mysql
    environment:
      RAILS_ENV: development
      RAKE_ENV: development
      DATABASE_HOST: mysql
      DATABASE_NAME: redu_development
      DATABASE_USER: root
      DATABASE_PASSWORD: password
    volumes:
      - .:/app  # optional, for local dev changes to reflect
    stdin_open: true
    tty: true

  mysql:
    image: mysql:5.6
    container_name: redu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: redu_development
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

