development:
  adapter: mysql2
  username: root
  password: password
  database: redu_development
  host: redu_mysql
production:
  adapter: mysql2
  username: root
  password:
  database: redu_production
  host: localhost
performance:
  adapter: mysql2
  username: root
  password:
  database: redu_performance
  host: localhost
staging:
  adapter: mysql2
  username: root
  password:
  database: redu_staging
  host: localhost
#test:
#  adapter: mysql2
#  username: root
#  password:
#  database: redu_test
#  host: localhost
